title: SPECs
baseURL: "https://specs.scientific-python.org"
languageCode: en-us
theme: scientific-python-hugo-theme
DefaultContentLanguage: en
relativeURLs: true
disableKinds: ["term", "taxonomy"]
markup:
  highlight:
    noClasses: false

params:
  description: Community developed and owned ecosystem for scientific computing

  images:
    - /images/logo.svg

  post_meta:
    - author
    - date

  style:
    vars:
      highlightColor: "#004811"
      menuHighlightColor: "#5ca038"

  navbarlogo:
    image: logo.svg
    altText: A green tree on a white hill at the end of a green path in the shape of the letter 'S'.
    text: SPECs
    link: /

  navbar:
    - title: Home
      url: /
    - title: Blog
      url: https://blog.scientific-python.org/
    - title: SPECs
      url: https://specs.scientific-python.org/

  hero:
    # Main hero title
    title: SPECs
    # Hero image (from static/images/___)
    image: logo.svg

  footer:
    logo: logo.svg
    socialmediatitle: ""
    socialmedia:
      - link: https://scientific-python.org
        icon: scientific-python
      - link: https://github.com/scientific-python/
        icon: github
      - link: https://www.youtube.com/c/ScientificPython-org
        icon: youtube
      - link: https://twitter.com/scientific_py
        icon: twitter
      - link: https://facebook.com/scientific.python
        icon: facebook
      - link: https://www.instagram.com/scientific.python/
        icon: instagram
      - link: https://www.tiktok.com/@scientific.python
        icon: tiktok
      - link: https://discord.com/invite/vur45CbwMz
        icon: discord
      - link: https://blog.scientific-python.org/atom.xml
        icon: rss-feed
      - link: https://discuss.scientific-python.org
        icon: discourse

    quicklinks:
      column1:
        title: ""
        links:
          - text: About
            link: /purpose-and-process/
          - text: Roadmap
            link: /roadmap/
          - text: Code of Conduct
            link: https://scientific-python.org/code_of_conduct/
      column2:
        title: "Maintainers"
        links:
          - text: Community
            link: https://scientific-python.org/community/
          - text: Calendars
            link: https://scientific-python.org/calendars/
          - text: Summits
            link: https://scientific-python.org/summits/
      column3:
        links:
          - text: Press kit
            link: /press-kit
